### ISSUE TITLE
Errors in chat when user leaves room

### ISSUE THREAD

**Issue by ojack** [culturehubnyc/LiveLab#19]

**Comment by tongwu226** [comment]
**March 31, LiveLab 1.2.0 with Ojack Version **
- Errors in chat when user leaves room. 
(No log)

**Comment by ojack** [comment]
Leaving initial title and linking to https://github.com/culturehubnyc/LiveLab/issues/14 which is about error logging and reporting.

**Comment by ojack** [comment]
Updated v1.3.x
