### ISSUE TITLE
Audio Volumn/Icon Color Reset Bug

### ISSUE THREAD

**Issue by chanaver** [culturehubnyc/LiveLab#28]
speaker icon issue 

I turn on the speaker button and after 20sec it change color but still  can hear
<img width="1386" alt="Screen Shot 2020-04-02 at 10 36 06 AM" src="https://user-images.githubusercontent.com/17872909/78262042-02f64380-74ce-11ea-9718-c753fe81cd68.png">

**Comment by tongwu226** [comment]
**Dress rehearsal observation on April 3rd:** 
When someone comes in or out of the room it resets the audio icon to default off. (The lady on the left bottom corner just came in, and everyone's audio icon turned white (On --> off). 

![Screen Shot 2020-04-03 at 4 09 49 PM](https://user-images.githubusercontent.com/21051323/78401523-ebe74c80-75c6-11ea-9ff6-54ca95d3c600.png)

**Comment by ojack** [comment]
Updated v1.3.x
