### ISSUE TITLE
Mute/Unmute All with 1 click? 

### ISSUE THREAD

**Issue by tongwu226** [culturehubnyc/LiveLab#29]
The hear-you-no conversation happens a lot. And the default OFF of the audio track is very inconvenient and frustrating. And the audio icon isn't clear enough for newly join people to realize and click on. 

1) Audio default ON 
2) Change the audio icon to text, or add text to do mute/unmute 
3) Change the speaker icon to text, or add text to do speaker on/off 
4) 1-click to unmute/mute all audio

**Comment by ojack** [comment]
Updated v1.3.x
