### ISSUE TITLE
Name randomly switching 

### ISSUE THREAD

**Issue by tongwu226** [culturehubnyc/LiveLab#30]
When someone leave the room, occasionally this person's nickname got switched to the box next to it. 

And no error observed in the console log. 
![Screen Shot 2020-04-03 at 5 19 17 PM](https://user-images.githubusercontent.com/21051323/78405963-9cf1e500-75cf-11ea-8031-18de33367b89.png)

**Comment by ojack** [comment]
Updated v1.3.x
