### ISSUE TITLE
Camera not requested on page load

### ISSUE THREAD

**Issue by ojack** [culturehubnyc/LiveLab#35]
![Screenshot from 2020-04-14 11-22-40](https://user-images.githubusercontent.com/4909769/79211352-72f9b780-7e46-11ea-9f05-47dac2c93c0d.png)

No indication or option to allow camera, no errors reported in console. 

Operating system: Chromium on Ubuntu

**Steps to Reproduce:**
1. Click lock next to address bar
2. Click 'site settings'
3. set camera and microphone to 'Ask(default)'
![Screenshot from 2020-04-14 11-51-31](https://user-images.githubusercontent.com/4909769/79211536-a89ea080-7e46-11ea-9c27-4b3e39fb46d5.png)
4. reload page

**To fix:**
Go to site settings as above, set camera and microphone to 'allow'.

**Comment by culturehubnyc** [comment]
This issue is now migrated to https://github.com/CultureHub/LiveLab/issues/3 for further discussion and update
