### ISSUE TITLE
Initiation: Media Settings - Audio Section

### ISSUE THREAD

**Issue by culturehubnyc** [culturehubnyc/LiveLab#4]
<img width="753" alt="Screen Shot 2020-03-26 at 12 33 06 AM" src="https://user-images.githubusercontent.com/33526300/77984997-2ad48400-72e1-11ea-8102-7ee512431600.png">

- [x] **Create a section within the media setting for audio** (top right)

1. Icon that shows the input level 
2. Options to mute yourself before joining the call (need?)

**Comment by ojack** [comment]
Audio settings should include controls for :
- echo cancellation
- noiseSupression
- autoGainLevel

**Comment by bcnyc** [comment]
We should also remove the speaker button under your own media stream. And is it possible to control users audio on independent sliders?

**Comment by ojack** [comment]
I actually just added this on ojack version (speaker button under your own
stream),

And yes. Maybe it makes sense to have audio control on the show control
page, a set of sliders that looks kind of like a mixer where you could
individually change volumes?

**Comment by bcnyc** [comment]
Show control audio mixer would be rad!

**Comment by culturehubnyc** [comment]
The layout of the advanced setting page has been updated for public release. 
- Updated the menu title to "Advanced Settings" 
- Added Audio controls, echo cancellation, noise suppression,  auto Gain, 
- Added audio indicator 
- Added cancel / save / exit buttons

**Comment by ojack** [comment]
Updated v1.3.x
