### ISSUE TITLE
Initiation: Media Settings - Applying Constraints to Video Feed 

### ISSUE THREAD

**Issue by culturehubnyc** [culturehubnyc/LiveLab#5]
![Screen Shot 2020-03-31 at 1 22 54 AM](https://user-images.githubusercontent.com/33526300/77990448-5c544c00-72ef-11ea-9953-69ad91a85000.png)

- [x] **Bug fix:** 

The input would show “NaN” when the user deletes the input, and stops the user from deleting the “NaN” or retyping content.  

![Screen Shot 2020-03-31 at 1 22 57 AM](https://user-images.githubusercontent.com/33526300/77990474-74c46680-72ef-11ea-99c9-4bb42c76699d.png)

- [ ] **Constraints Options**
Create Options for both preset resolutions and freeform adjustment, and move the original design to be under the “free-form” option. 

> Do we provide resolution options like 
> HD 1920x1080
> SD 720 x 480
> or we provide ratio options to arrange the video ratio?

**Comment by culturehubnyc** [comment]
The layout for video constrains has been updated for public release: 
- improved the layout

**Comment by ojack** [comment]
NaN error fixed in v1.3.x
