### ISSUE TITLE
Initiation: Media Settings - Save & Exit

### ISSUE THREAD

**Issue by culturehubnyc** [culturehubnyc/LiveLab#6]
<img width="753" alt="Screen Shot 2020-03-26 at 12 33 06 AM" src="https://user-images.githubusercontent.com/33526300/77990753-2499d400-72f0-11ea-8c67-73c5c2a03ca4.png">

- [x] **Save and Exit button** (bottom right) 

Create a "save settings” button for exiting Media Settings instead of clicking on the “X” on the  top right corner

**Comment by tongwu226** [comment]
Cancel / Save / Exit functions have been added.
