### ISSUE TITLE
Main Workspace: Audio UI

### ISSUE THREAD

**Issue by culturehubnyc** [culturehubnyc/LiveLab#7]
<img width="619" alt="Screen Shot 2020-03-31 at 1 40 03 AM" src="https://user-images.githubusercontent.com/33526300/77990920-907c3c80-72f0-11ea-92af-f023b18f8e0e.png">

### **Current UI Issue:** 
**1. Your own audio track - Default MUTED:** You don't listen to your audio looping 
**2. Your Mic - Default ON:** You join the session with your audio on 
**3. Other Audio Tracks - Default MUTED:** Others join the conversation but you click on their volume button to hear their audio (Users are usually unaware and confused)  

### **UI Adjustment:** 

- [x] **Remove the listen-to-your-own-audio function**

<img width="186" alt="Screen Shot 2020-03-31 at 1 45 59 AM" src="https://user-images.githubusercontent.com/33526300/77991276-67a87700-72f1-11ea-809d-cbe76ed07980.png">

- [x] **Adjust Your Audio UI** 
1. Keep only one mic button (UNMUTED: white / MUTED: RED)
2. Default ON / Optional OFF on the advanced menu 

- [x] **Adjust Others' Audio UI**
1. Keep the audio button, or change it to a mute/unmuted text button (ON: green / OFF: RED)
2. Default OFF: Keep the default setting to mute others’ mics when they join the conversation

----
**_Zoom Example_** 
_Zoom allows participants to mute/unmute themselves as well as other participants during a video call through a text button on the top right of each video window.
If one is muted, there’s a red icon of a crossed mic beside the participant’s name on the button left._ 

<img width="407" alt="Screen Shot 2020-03-31 at 2 03 39 AM" src="https://user-images.githubusercontent.com/33526300/77992333-dedf0a80-72f3-11ea-8dc7-82b59a35c443.png">

**Comment by tongwu226** [comment]
Audiotrack volume reset / icon color reset issue: #28 / 04.03.20

**Comment by tongwu226** [comment]
Audio functions user experience improvement and confusions  #29 /04.03.20

**Comment by tongwu226** [comment]
- Self mute / unmute button has been integrated into the side-menu bar in the public release version layout. 
- Others' Mute/ Unmuted indicator has been integrated into the floating name tag.
