### ISSUE TITLE
Main Workspace: Panels | Collapsible Panel

### ISSUE THREAD

**Issue by culturehubnyc** [culturehubnyc/LiveLab#8]
<img width="711" alt="Screen Shot 2020-03-31 at 2 07 04 AM" src="https://user-images.githubusercontent.com/33526300/77992569-56ad3500-72f4-11ea-8132-08202b1e8bc8.png">

- [x] **Collapsible Panels**
Make the panel section collapsible to improve simplicity and provide more displaying space.

**Comment by tongwu226** [comment]
The main workspace now has a collapsible side menu bar. The original shared media panel has been simplified and integrated as the "Participant" pop up window.
