### ISSUE TITLE
Main Workspace: Hangup, globally and individually

### ISSUE THREAD

**Issue by ojack** [culturehubnyc/LiveLab#9]
Hangup button currently throws error.
Question -- should users be able to hangup their main communication stream, or only streams that they have added later on?

**Comment by bcnyc** [comment]
I think it is important to have a global hang up button which ends all streams. Being able to hang up added streams individually would also be nice if it isn't too much trouble.

**Comment by ojack** [comment]
Would the global button be equivalent to closing the tab/browser, or would
it do something slightly different?

**Comment by bcnyc** [comment]
It would do the same thing...just more intuitive to the average user.

**Comment by culturehubnyc** [comment]
- [ ] **Hangup Button** 

_For Public Release:_ Create a hangup button on the main workspace to ends all streams and exit.

**Comment by tongwu226** [comment]
- Global hangup button has been integrated into the side menu bar. 
onClick() -> Ending page. 
- Individual hangup is represented as the "trashcan" icon on each streams you have added. (You can only hang up your streams)
